// Generated by ReScript, PLEASE EDIT WITH CARE

import PokedexPromiseV2 from "pokedex-promise-v2";

let pokedex = new PokedexPromiseV2();

function stripPkmn(pkmn) {
  return {
    id: pkmn.id,
    name: pkmn.name,
    sprites: {
      front_default: pkmn.sprites.front_default
    }
  };
}

async function getPokemonByIds(ids) {
  try {
    let pkmns = await pokedex.getPokemonByName(ids);
    if (ids.some(i => i > 700)) {
      return {
        TAG: "Error",
        _0: "Higher than 70"
      };
    } else {
      return {
        TAG: "Ok",
        _0: pkmns.map(stripPkmn)
      };
    }
  } catch (exn) {
    return {
      TAG: "Error",
      _0: "Unexpected error in while taking to pokemon api"
    };
  }
}

export {
  getPokemonByIds,
}
/* pokedex Not a pure module */
