// Generated by ReScript, PLEASE EDIT WITH CARE

import PokedexPromiseV2 from "pokedex-promise-v2";

let pokedex = new PokedexPromiseV2();

function stripPkmn(pkmn) {
  return {
    id: pkmn.id,
    name: pkmn.name,
    sprites: {
      front_default: pkmn.sprites.front_default
    }
  };
}

async function getPokemonByIds(ids) {
  let pkmns = await pokedex.getPokemonByName(ids);
  return pkmns.map(stripPkmn);
}

export {
  getPokemonByIds,
}
/* pokedex Not a pure module */
