// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Array from "rescript/lib/es6/Stdlib_Array.js";
import PokedexPromiseV2 from "pokedex-promise-v2";

let pokedex = new PokedexPromiseV2();

function stripPkmn(pkmn) {
  return {
    id: pkmn.id,
    name: pkmn.name,
    sprites: {
      front_default: pkmn.sprites.front_default
    }
  };
}

async function getPokemonByIds(ids) {
  try {
    let pkmns = await pokedex.getPokemonByName(ids);
    if (ids.some(i => i > 700)) {
      return {
        TAG: "Error",
        _0: "Higher than 70"
      };
    } else {
      return {
        TAG: "Ok",
        _0: pkmns.map(stripPkmn)
      };
    }
  } catch (exn) {
    return {
      TAG: "Error",
      _0: "Unexpected error in while taking to pokemon api"
    };
  }
}

function parseGame(game) {
  let match = game.toLocaleLowerCase();
  switch (match) {
    case "both" :
      return "Both";
    case "firered" :
      return "FireRed";
    case "leafgreen" :
      return "LeafGreen";
    default:
      return "NotSure";
  }
}

async function getGame(id) {
  let encounters = await fetch("https://pokeapi.co/api/v2/pokemon/" + id.toString() + "/encounters").then(prim => prim.json());
  let inGameLocations;
  inGameLocations = Array.isArray(encounters) ? new Set(encounters.flatMap(json => {
      if (typeof json !== "object" || json === null || Array.isArray(json)) {
        return [];
      }
      let match = json.location_area;
      if (typeof match !== "object" || match === null || Array.isArray(match)) {
        return [];
      }
      let tmp = match.name;
      if (typeof tmp !== "string") {
        return [];
      }
      let versionDetails = json.version_details;
      if (Array.isArray(versionDetails)) {
        return Stdlib_Array.filterMap(versionDetails, json => {
          if (typeof json !== "object" || json === null || Array.isArray(json)) {
            return;
          }
          let match = json.version;
          if (typeof match !== "object" || match === null || Array.isArray(match)) {
            return;
          }
          let name = match.name;
          if (typeof name !== "string") {
            return;
          }
          switch (name) {
            case "firered" :
            case "leafgreen" :
              return name;
            default:
              return;
          }
        });
      } else {
        return [];
      }
    })) : new Set();
  let inLeaf = inGameLocations.has("leafgreen");
  let inFirered = inGameLocations.has("firered");
  if (inLeaf) {
    if (inFirered) {
      return "Both";
    } else {
      return "LeafGreen";
    }
  } else if (inFirered) {
    return "FireRed";
  } else {
    return "NotSure";
  }
}

export {
  getPokemonByIds,
  parseGame,
  getGame,
}
/* pokedex Not a pure module */
