// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Pokedex from "../bindings/Pokedex.jsx";
import * as Stdlib_Array from "rescript/lib/es6/Stdlib_Array.js";
import * as InfiniteScroll from "../components/InfiniteScroll.jsx";
import * as JsxRuntime from "react/jsx-runtime";

import '../styles.css'
;

async function $$default(param) {
  let initial = await Pokedex.getPokemonByIds(Stdlib_Array.fromInitializer(10, idx => idx + 1 | 0));
  let loadMore = async skip => {
    'use server';
    let ids = Stdlib_Array.fromInitializer(10, idx => skip + idx | 0);
    return await Pokedex.getPokemonByIds(ids);
  };
  let tmp;
  tmp = initial.TAG === "Ok" ? <InfiniteScroll.make
      items={initial._0}
      loadMore={loadMore}
    /> : initial._0;
  return <div
    className={"w-300 mx-auto mt-6"}
  >
    {import.meta.viteRsc.loadCss()}
    <h1
      className={"text-2xl font-bold mb-6"}
    >
      {"Infinite Scroll"}
    </h1>
    {tmp}
  </div>;
}

let Infinite$default = $$default;

async function getConfig() {
  return {
    render: "dynamic"
  };
}

let $$default$1 = Infinite$default;

export {
  $$default$1 as default,
  getConfig,
}
/*  Not a pure module */
