// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Pokedex from "../bindings/Pokedex.jsx";
import * as Bunsqlite from "bun:sqlite";
import * as Stdlib_Array from "rescript/lib/es6/Stdlib_Array.js";
import * as JsxRuntime from "react/jsx-runtime";

import '../styles.css'
;

async function getData() {
  let db = new Bunsqlite.Database("db.sqlite");
  let statement = db.query("SELECT * FROM pokemon");
  let pkmns = statement.all();
  db.close();
  return Stdlib_Array.filterMap(pkmns, pkmn => {
    if (typeof pkmn !== "object" || pkmn === null || Array.isArray(pkmn)) {
      return;
    }
    let id = pkmn.id;
    if (typeof id !== "number") {
      return;
    }
    let name = pkmn.name;
    if (typeof name !== "string") {
      return;
    }
    let game = pkmn.game;
    if (typeof game === "string") {
      return {
        id: id | 0,
        name: name,
        game: Pokedex.parseGame(game)
      };
    }
    
  });
}

async function $$default(param) {
  let pkmns = await getData();
  return <div>
    {import.meta.viteRsc.loadCss()}
    <h1>
      {"Overview"}
    </h1>
    <div
      className={"flex flex-wrap"}
    >
      {pkmns.map(pkmn => {
        let match = pkmn.game;
        let bg;
        switch (match) {
          case "FireRed" :
            bg = "bg-red-400";
            break;
          case "LeafGreen" :
            bg = "bg-lime-300";
            break;
          case "Both" :
            bg = "bg-linear-135/hsl from-lime-300 from-49% to-red-400 to-51%";
            break;
          case "NotSure" :
            bg = "bg-gray-100";
            break;
        }
        return <div
          key={pkmn.id.toString()} 
          className={"border border-gray-200 rounded m-2 flex flex-col items-center justify-center h-[150px] w-[150px] " + bg}
        >
          <h2
            className={"text-lg font-semibold capitalize mb-2 flex items-center"}
          >
            <span
              className={"text-xs italic mr-1"}
            >
              {pkmn.id}
            </span>
            {pkmn.name}
          </h2>
          <div
            className={"w-[100px] h-[100px] bg-no-repeat -translate-y-3"}
            style={{
              backgroundImage: "url(/images/spritesheet.png)",
              backgroundPosition: "-" + ((pkmn.id - 1 | 0) * 100 | 0).toString() + "px 0"
            }}
          />
        </div>;
      })}
    </div>
  </div>;
}

let Overview$default = $$default;

let $$default$1 = Overview$default;

export {
  getData,
  $$default$1 as default,
}
/*  Not a pure module */
