// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Pokedex from "../bindings/Pokedex.jsx";
import * as Stdlib_Array from "rescript/lib/es6/Stdlib_Array.js";
import * as JsxRuntime from "react/jsx-runtime";

import '../styles.css'
;

async function $$default(param) {
  let pkmns = await Pokedex.getPokemonByIds(Stdlib_Array.fromInitializer(150, idx => idx + 1 | 0));
  let tmp;
  tmp = pkmns.TAG === "Ok" ? <div
      className={"flex flex-wrap"}
    >
      {pkmns._0.map(pkmn => <div
        key={pkmn.id.toString()} 
        className={"border m-2 flex flex-col"}
      >
        <h2
          className={"text-center"}
        >
          {pkmn.name}
        </h2>
        <div
          className={"w-[100px] h-[100px] bg-no-repeat"}
          style={{
            backgroundImage: "url(/images/spritesheet.png)",
            backgroundPosition: "-" + ((pkmn.id - 1 | 0) * 100 | 0).toString() + "px 0"
          }}
        />
      </div>)}
    </div> : pkmns._0;
  return <div>
    {import.meta.viteRsc.loadCss()}
    <h1>
      {"Overview"}
    </h1>
    {tmp}
  </div>;
}

let Overview$default = $$default;

let $$default$1 = Overview$default;

export {
  $$default$1 as default,
}
/*  Not a pure module */
