'use client'
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Stdlib_Array from "rescript/lib/es6/Stdlib_Array.js";
import * as Stdlib_Option from "rescript/lib/es6/Stdlib_Option.js";
import * as Stdlib_Result from "rescript/lib/es6/Stdlib_Result.js";
import * as Primitive_option from "rescript/lib/es6/Primitive_option.js";
import * as JsxRuntime from "react/jsx-runtime";
import * as ReactVirtual from "@tanstack/react-virtual";

function InfiniteScroll(props) {
  let loadMore = props.loadMore;
  let parentRef = React.useRef(null);
  let match = React.useTransition();
  let startTransition = match[1];
  let match$1 = React.useActionState(async (currentItems, param) => {
    if (currentItems.TAG !== "Ok") {
      return {
        TAG: "Error",
        _0: currentItems._0
      };
    }
    let items = currentItems._0;
    let skip = Math.min(141, items.length);
    let newItems = await loadMore(skip);
    return Stdlib_Result.map(newItems, newItems => items.concat(newItems));
  }, {
    TAG: "Ok",
    _0: props.items
  });
  let isPending = match$1[2];
  let loadMore$1 = match$1[1];
  let allItems = match$1[0];
  let tmp;
  tmp = allItems.TAG === "Ok" ? allItems._0.length : 0;
  let virtualizer = ReactVirtual.useVirtualizer({
    count: tmp,
    getScrollElement: () => parentRef.current,
    estimateSize: param => 100,
    onChange: virtualizer => {
      if (allItems.TAG !== "Ok") {
        return;
      }
      let items = allItems._0;
      if (items.length < 151 && !isPending) {
        return Stdlib_Option.forEach(Stdlib_Array.last(virtualizer.getVirtualItems()), param => {
          if (param.index > (items.length - 10 | 0)) {
            return startTransition(() => {
              loadMore$1();
            });
          }
          
        });
      }
      
    },
    initialRect: {
      width: 100,
      height: 400
    }
  });
  let tmp$1;
  if (allItems.TAG === "Ok") {
    let allItems$1 = allItems._0;
    tmp$1 = <div
      className={"w-full relative"}
      style={{
        height: virtualizer.getTotalSize().toString() + "px"
      }}
    >
      {virtualizer.getVirtualItems().map(item => {
        let pkmn = allItems$1[item.index];
        if (pkmn !== undefined) {
          return <div
            key={item.key} 
            className={"absolute"}
            style={{
              height: item.size.toString() + "px",
              left: "50%",
              top: item.start.toString() + "px"
            }}
          >
            <img
              className={"h-full -translate-x-1/2"}
              alt={pkmn.name}
              src={pkmn.sprites.front_default}
            />
          </div>;
        } else {
          return null;
        }
      })}
    </div>;
  } else {
    tmp$1 = <div
      className={"alert alert-error mx-6"}
      role={"alert"}
    >
      <svg
        className={"h-6 w-6 shrink-0 stroke-current"}
        fill={"none"}
        viewBox={"0 0 24 24"}
        xmlns={"http://www.w3.org/2000/svg"}
      >
        <path
          d={"M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z"}
          strokeLinecap={"round"}
          strokeLinejoin={"round"}
          strokeWidth={"2"}
        />
      </svg>
      <span>
        {allItems._0}
      </span>
    </div>;
  }
  return <>
    <div
      ref={Primitive_option.some(parentRef)}
      className={"h-[400px] w-full overflow-auto border border-sky-100 content-center"}
    >
      {tmp$1}
    </div>
    {isPending ? <progress
        className={"progress progress-primary w-56 mx-auto block mt-4"}
      /> : null}
  </>;
}

let make = InfiniteScroll;

export {
  make,
}
/* react Not a pure module */
