// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Pokedex from "../src/bindings/Pokedex.jsx";
import * as Process from "process";
import * as Bunsqlite from "bun:sqlite";
import * as Stdlib_Array from "rescript/lib/es6/Stdlib_Array.js";

let db = new Bunsqlite.Database("db.sqlite", {
  create: true
});

db.query("\nCREATE TABLE IF NOT EXISTS pokemon (\n    id INTEGER PRIMARY KEY AUTOINCREMENT,\n    name TEXT NOT NULL,\n    game TEXT NOT NULL,\n    created_at TEXT DEFAULT CURRENT_TIMESTAMP,\n    updated_at TEXT DEFAULT CURRENT_TIMESTAMP\n);\n").run();

let ids = Stdlib_Array.filterMap(Stdlib_Array.fromInitializer(150, idx => {
  let id = idx + 1 | 0;
  let exists = db.query("SELECT id FROM pokemon WHERE id = @id").get({
    "@id": id
  });
  if (exists == null) {
    return id;
  }
  
}), id => id);

let pkmms = await Pokedex.getPokemonByIds(ids);

let insertStatement = db.query("INSERT INTO pokemon (id, name, game) VALUES (@id, @name, @game)");

if (pkmms.TAG === "Ok") {
  await Promise.all(pkmms._0.map(async pkmm => {
    let game = await Pokedex.getGame(pkmm.id);
    return insertStatement.run({
      "@id": pkmm.id,
      "@name": pkmm.name,
      "@game": game
    });
  }));
} else {
  console.log(pkmms._0);
  Process.exit(1);
}

db.close();

export {
  db,
  ids,
  pkmms,
  insertStatement,
}
/* db Not a pure module */
