// Generated by ReScript, PLEASE EDIT WITH CARE

import Sharp from "sharp";
import * as Nodepath from "node:path";
import * as Nodebuffer from "node:buffer";
import * as Stdlib_Array from "rescript/lib/es6/Stdlib_Array.js";

let Buffer = {};

let Sharp$1 = {};

let Path = {};

async function downloadImage(url, index) {
  let response = await fetch(url);
  let arrayBuffer = await response.arrayBuffer();
  let buffer = await Sharp(Nodebuffer.Buffer.from(arrayBuffer)).resize({
    width: 100,
    height: 100,
    fit: "cover"
  }).png().toBuffer();
  return {
    input: buffer,
    top: 0,
    left: index * 100 | 0
  };
}

let sources = Stdlib_Array.fromInitializer(150, idx => "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/" + (idx + 1 | 0).toString() + ".png");

let images = await Promise.all(sources.map(downloadImage));

let totalWidth = 100 * sources.length | 0;

await Sharp({
  create: {
    width: totalWidth,
    height: 100,
    channels: 4,
    background: {
      r: 0,
      g: 0,
      b: 0,
      alpha: 0
    }
  }
}).composite(images).png().toFile(Nodepath.resolve(import.meta.dirname, "../public/images/spritesheet.png"));

let thumbnailSize = 100;

let url = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png";

export {
  Buffer,
  Sharp$1 as Sharp,
  Path,
  thumbnailSize,
  url,
  downloadImage,
  sources,
  images,
  totalWidth,
}
/* sources Not a pure module */
